---
- name: Create volume
  openstack.cloud.volume:
     cloud: "{{ cloud }}"
     state: present
     size: 1
     display_name: ansible_volume
     display_description: Test volume
  register: vol

- name: Create volume snapshot
  openstack.cloud.volume_snapshot:
    cloud: "{{ cloud }}"
    state: present
    display_name: ansible_volume_snapshot
    volume: ansible_volume
  register: vol_snap

- name: Get snapshot info
  openstack.cloud.volume_snapshot_info:
    cloud: "{{ cloud }}"
    name: ansible_volume_snapshot
  register: snap_info
  ignore_errors: sdk_version is version('0.49', '<')

- name: Create volume backup
  openstack.cloud.volume_backup:
    cloud: "{{ cloud }}"
    state: present
    display_name: ansible_volume_backup
    volume: ansible_volume
  register: vol_backup
  ignore_errors: sdk_version is version('0.49', '<')

- name: Get backup info
  openstack.cloud.volume_backup_info:
    cloud: "{{ cloud }}"
    name: ansible_volume_backup
  register: backup_info
  ignore_errors: sdk_version is version('0.49', '<')

- debug: var=vol

- debug: var=vol_backup

- debug: var=backup_info

- debug: var=snap_info

- name: Delete volume backup
  openstack.cloud.volume_backup:
    cloud: "{{ cloud }}"
    display_name: ansible_volume_backup
    state: absent
  ignore_errors: sdk_version is version(0.49, '<')

- name: Delete volume snapshot
  openstack.cloud.volume_snapshot:
    cloud: "{{ cloud }}"
    display_name: ansible_volume_snapshot
    volume: ansible_volume
    state: absent

- name: Delete volume
  openstack.cloud.volume:
     cloud: "{{ cloud }}"
     state: absent
     display_name: ansible_volume

- include_tasks: volume_info.yml
